"""empty message

Revision ID: 5ed707180244
Revises: 1be038caae71
Create Date: 2025-01-06 20:23:01.069388

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ed707180244'
down_revision = '1be038caae71'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('selected_numbers', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_game_id_fkey', type_='foreignkey')
        batch_op.drop_column('game_id')
        batch_op.drop_column('selected_numbers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_numbers', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('game_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('users_game_id_fkey', 'games', ['game_id'], ['id'])

    op.drop_table('tickets')
    # ### end Alembic commands ###
