"""empty message

Revision ID: 9426e47a3a11
Revises: 91f7a4a29923
Create Date: 2025-01-06 15:26:31.194985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9426e47a3a11'
down_revision = '91f7a4a29923'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_numbers', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('selected_numbers')

    # ### end Alembic commands ###
