"""empty message

Revision ID: eec37dc013e0
Revises: 
Create Date: 2025-01-08 17:34:08.442883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec37dc013e0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preference', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('reference_id', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('total', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_column('status')
        batch_op.drop_column('total')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('reference_id')
        batch_op.drop_column('preference')

    # ### end Alembic commands ###
